from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Iterable, Sequence


class ModelProvider(ABC):
    name: str = "base"

    @abstractmethod
    async def generate(
        self,
        messages: Sequence[dict[str, str]],
        *,
        system: str | None = None,
        tools: list[dict[str, Any]] | None = None,
        temperature: float = 0.7,
        max_tokens: int | None = None,
        stream: bool = False,
        metadata: dict[str, Any] | None = None,
    ) -> str:
        raise NotImplementedError


class InMemoryModelProvider(ModelProvider):
    name = "inmemory"

    async def generate(
        self,
        messages: Sequence[dict[str, str]],
        *,
        system: str | None = None,
        tools: list[dict[str, Any]] | None = None,
        temperature: float = 0.7,
        max_tokens: int | None = None,
        stream: bool = False,
        metadata: dict[str, Any] | None = None,
    ) -> str:
        prompt = "\n".join(f"{m.get('role', 'user')}: {m.get('content', '')}" for m in messages)
        if "calculate" in prompt.lower() or "math" in prompt.lower():
            return "I can help with the calculation. Please provide the exact formula or expression."
        if "time dilation" in prompt.lower():
            return (
                "Time dilation is a consequence of special relativity: clocks moving relative to an observer "
                "run slower by a factor gamma = 1 / sqrt(1 - v^2/c^2). For a spacecraft at 0.99c, gamma is "
                "approximately 7.09, so one Earth year corresponds to about 0.141 years of proper time on the craft."
            )
        return "This is a mock model response generated by the OMNIA in-memory provider. It is suitable for testing the architecture and orchestration flow."


PROVIDERS = {
    "inmemory": InMemoryModelProvider,
    "mock": InMemoryModelProvider,
}


def get_model_provider(name: str | None = None) -> ModelProvider:
    provider_name = (name or "inmemory").lower()
    provider_cls = PROVIDERS.get(provider_name)
    if provider_cls is None:
        raise ValueError(f"Unsupported model provider: {provider_name}")
    return provider_cls()
